name             'sensu_community_plugins'
maintainer       'Ulf Mansson'
maintainer_email 'ulf.mansson@recordedfuture.com'
license          'Apache 2.0'
description      'Installs the community plugins for Sensu'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.0.1'
supports         'ubuntu', '>= 0.0.0'
depends          'git', '>= 0.0.0'
depends          'sensu'
